import '../css/base/reset.css';
import '../css/base/base.css';
import '../css/base/state.css';
import '../css/base/animation.css';
import '../css/base/typography.css';
import '../css/base/spacing.css';
import '../css/base/version.css';
import '../css/base/zIndex.css';
import '../css/component/logo.css';
import '../css/component/button.css';
import '../css/component/collapse.css';
import '../css/component/font.css';
import '../css/component/form.css';
import '../css/component/icon.css';
import '../css/component/fontawesome.css';
import '../css/component/utilities.css';
import '../css/component/grid.css';
import '../css/component/bookmark.css';
import '../css/component/theme.css';
import '../css/component/modal.css';
import '../css/component/layout.css';
import '../css/component/menu.css';
import '../css/component/toolbar.css';
import '../css/component/autoSuggest.css';

import { data } from './data';
import { state } from './state';
import { control } from './control';
import { layout } from './layout';
import { toolbar } from './toolbar';
import { menu } from './menu';
import { bookmark } from './bookmark';
import { grid } from './grid';
import { theme } from './theme';
import { modal } from './modal';
import { autoSuggest } from './autoSuggest';
import { version } from './version';
import { keyboard } from './keyboard';

console.log(data.saveName + ' version:', version.number, version.name);
data.init();
layout.init();
grid.init();
bookmark.init();
theme.init();
toolbar.init();
menu.init();
modal.init();
autoSuggest.init();
keyboard.init();
